### ISSUE TITLE
[Backend] Dokumentasi Alur Code Review

### ISSUE THREAD

**Issue by aldidoanta** [jabardigitalservice/development-guides#1]
# Overview
Membuat standar alur code review di GitHub. Alur yang dibuat akan coba diterapkan di [repository group Labkes](https://github.com/jabardigitalservice?q=labkes&type=&language=).

# Pertanyaan/TODOs:
1. Representasi alurnya akan seperti apa? Teks biasa? Apakah perlu dibuat flowchart?
2. Eksplorasi GitHub Actions yang dapat mempermudah alur code review. Salah satu referensi awal dapat dilihat di https://github.com/sdras/awesome-actions#pull-requests

# Notes
Tambahan dari kang @firmanhxc 
Ketentuan utk Pull Request :
- Diharuskan mention tim labkes dan lead
- PR akan dilakukan ketika salah satu tim internal dan salah satu lead sudah approve

@jabardigitalservice/jds-backend Mangga kalau ada masukan.

**Comment by sandisunandar99** [comment]
mungin saya nambahin dikit
1. untuk pull request sebisa mungkin judul nya jelas di PR itu apa
2. pendeskripsian dari judul kalo bisa lebih runut contoh simple yg biasa saya lakuin kaya gini: 

### OVERVIEW / JUDUL PR = MEMBUAT FITUR IMPORT
1. menambahkan fitur baru import di menu laporan harian
2. fitur import ada validasi per role (admin : all kota/kab) (dinas prov: all kota/kab) (dinas kota/kab: all kecamatan di wilayah kota/kab nya)
3. max import 5000 row per 1 file max 10 MB
4. login required


mungkin kaya gitu sederhana nya,, mungkin bisa ada saran lain bagi saya + temen2 dsini @aldidoanta @firmanhxc

**Comment by aldidoanta** [comment]
Kang @sandisunandar99 ada PR yang bisa jadi contoh kang?
